### PR TITLE
Workflow objects in undo stacks

### PR DESCRIPTION
**Pull request by Cryaaa**
@haesleinhuepf 
This is the PR implementing undo and redo functionality to workflows. It is a draft since not all functions have docstrings yet and more importantly the code on which this is based on (with some heavy modification by now) is from a different [github library](https://github.com/ArjanCodes/2021-command-undo-redo). Luckily it has the MIT license but I was unsure where we have to mention his name exactly, since I do not want to bring this library into legal troubles :D. Maybe you can remind me once more and I will change things but code-wise I do not think things are going to change much.

### CODE REVIEW

**Comment by Cryaaa** [comment]
@haesleinhuepf:
I have already figured out why tests are failing and it seems that the typing library for type annotations differs between python 3.7 and 3.8 so I might just remove this Protocol object.

**Comment by Cryaaa** [comment]
Maybe I need to do some research on codecov sice this always fails for my PR's to your libraries. Also as a side note I maybe should write some tests for undo and redo functions.

**Comment by Cryaaa** [comment]
Checklist for PR:

- [ ] Remove any debugging prints
- [ ] Write tests for undo redo functions
- [ ] Finalise Docstrings
- [ ] Find a more elegant solution for the problem when arrays are given to workflow instead of layer names

**Comment by haesleinhuepf** [comment]
Big thanks Ryan @Cryaaa !

**Pull request merged**
